### ISSUE TITLE
Invalid response issue when null in jsonp callback

### ISSUE THREAD

**Issue by mdaleki** [resty-gwt/resty-gwt#103]
I think there is a bug when jsonp callback method has null as argument in response.

Story:

1. Want to get current user on the server.
2. Send http://.../getUser?callback=__gwt.0.XX
3. Server return (there is no user currently): __gwt.0.XX(null);

(in case when user exist response will be e.g.: __gwt.0.XX({"email":"sample@email.com"}); )

4. Then in resty gwt I got "Response was NOT a valid JSON document", because of null parse in AbstractAsyncCallback:

  @Override
    final public void onSuccess(JavaScriptObject result) {
        try {
            GWT.log("Received http response for jsonp request", null);
            JSONObject json = new JSONObject(result); 
            GWT.log(json.toString(), null);
            callback.onSuccess(this.method, parseResult(json));
        } catch (Throwable e) {
            GWT.log("Could not parse response: " + e, e);
            callback.onFailure(this.method, e);
            return;
        }
    }

Suppouse there will be check if result is null and then call 

callback.onSuccess(this.method,null);

In an AbstractRequestCallback used for non JsonpMethod there is no issue when server returns null. Code check content of response and finally callback with null value was called so in my final MethodCallbackI can do:

@Override
			public void onSuccess(Method method, User response) {
				if (response == null) {
                          ...
                        }}

**Comment by Armageddon-** [comment]
fix should be in 473e6bcbbcb392dfe2bf6ffa20f086ae80c103f4
