### ISSUE TITLE
Encoding/Decoding Map with Integer key

### ISSUE THREAD

**Issue by pobrien1** [resty-gwt/resty-gwt#107]
Hello, I have been using Resty for a while now and think its great! However, I am now having a problem with encoding/decoding json where my DTOs contains a map with an integer key. Here is a simple example. For the example DTO below, my json returned from my test REST service looks like:

{"entry":{"6":"six","7":"seven","12":"twelve"}}.

The json keys are strings (which is correct). However, on the client side, the decoded object appears to contain a map with keys that are strings and not integer values as I would have expected. If I then try and encode the resulting object back to json using the same generated encoder/decoder I get an exception (presumably because it is expecting an integer key rather than the provided String key)

Am I missing something here? Perhaps I need to give resty some additional info?

Cheers

Paul

btw I am using resty-gwt 1.3.1

public class DTO {

```
public DTO(){

    entry = new HashMap<Integer, String>();

    entry.put(12,"twelve");
    entry.put(7, "seven");
    entry.put(6, "six");
}

public void setEntry(Map<Integer,String> entry){

    this.entry = entry;
}

public Map<Integer, String> getEntry(){

    return entry;
}

private Map<Integer,String> entry;
```

}

**Comment by aponyrko** [comment]
@mkristian "fixed along with complex types as keys" - can you provide any guidance as to how one would configure Jackson to write out complex keys? By default Jackson will do a toString() on the key object.

I've found this article but not sure if this is the format Resty will expect:
http://heli0s.darktech.org/jackson-serialize-map-with-non-string-key-in-fact-with-any-serializable-key-and-abstract-classes/

**Comment by mkristian** [comment]
@aponyrko restygwt first encodes the key as json and then makes a toString on the json object. yes, the link of yours does the same.
