### ISSUE TITLE
How to use restygwt's RestService with RestDatasource

### ISSUE THREAD

**Issue by skaluva** [resty-gwt/resty-gwt#118]
Hi,
I really got into bigger problem. I need to populate data in ListGrid so I'm attaching a RestDataSource (to leverage capabilities of client side filtering, caching etc.,) to the same in which i need to handle FETCH. 

But i have RestService as well in which FETCH related method with URL mappings is already defined. So i want to call this method as part of RestDatasource's FETCH operation. But couldn't understand how to integrate both.
RestService:

``` javascript
@GET
    @Path("/fetchServiceGroups")
    public void doFetchPGServiceGroups(@QueryParam("svnBranch") String svnBranch,MethodCallback<Set<String>> callback);

```

If you see above method, i'm returning Set<String> which i'm converting to Records in callback to set to ListGrid. If i directly use above call to set data to ListGrid, its working as expected.

But i want to leverage the capabilities of Datasource. So i want to integrate both. Please suggest me a way to do that.

**Comment by pedy711** [comment]
@skaluva I have the same problem. Did you manage to solve this?
