### ISSUE TITLE
Jersey REST Services with Status Code. Couldn't use with javax.ws.rs.Response object.

### ISSUE THREAD

**Issue by ashokkumarprajapati** [resty-gwt/resty-gwt#126]
I am using Jersey based web services and using RestyGWT based UI application to connect to it.

@GET
@Path("retrieve/{uuid}")
public Response retrieveSomething(@PathParam("uuid") String uuid) {
   return Response.ok(json, MediaType.APPLICATION_JSON).build();
}

Now my restyGWT service at client side is not able to recognize javax.rs.core.Response object.
As far as i can see, there could be 2 options for it to work : 
1. RestyGWT is able to resolve Response object.
2. RestyGWT should provide a way to by-pass check on server side interface using deferred binding.

Please suggest.

**Comment by glucas** [comment]
It would be nice if we could share interfaces (DirectRestService) that work with a JAX-RS Response object. Perhaps that could be accomplished with an annotation to indicate the desired response type for methods that return a JAX-RS Response.

**Comment by mkristian** [comment]
can the JAX-RS Response be "compiled" with gwt ?

**Comment by glucas** [comment]
Not sure, but even if so it is not intended to be exposed to the client. From the javadoc for javax.ws.rs.core.Response: "Defines the contract between a returned instance and the runtime when an application needs to provide meta-data to the runtime."
