### ISSUE TITLE
Cannot specify timezone for date formatting

### ISSUE THREAD

**Issue by lucidfox** [resty-gwt/resty-gwt#174]
The server expects dates to be passed as yyyy-MM-dd HH:mm:ss in UTC. While RestyGWT allows changing the date format string, it does not allow specifying the timezone and always formats and parses in the local timezone.

Implementing a change to the format function will be straightforward. Unfortunately, the parse function does not accept a TimeZone argument, so the parser might have to detect if "Z" or "z" is present in the format string, and handle the cases accordingly.

**Comment by mkristian** [comment]
@lucidfox git says your patch is in and this is fixed. closing
