### ISSUE TITLE
Can't create custom JSON encode/decode for java.sql.Timestamp

### ISSUE THREAD

**Issue by sykesd** [resty-gwt/resty-gwt#175]
We have some existing model classes with java.sql.Timestamp fields on them that we would like to use without modification with Resty-GWT. This requires a custom encoder/decoder.

I was able to write one and have it be used by setting the org.fusesource.restygwt.restyjsonserializergenerator configuration parameter. However, the generated class gets created in package java.sql. which Java then refuses to load (in DevMode at least) throwing a SecurityException.

Would it be possible to detect that the generated code will end up in a protected package, and generate it in a different package?

**Comment by Armageddon-** [comment]
Workaround added with #176
