### ISSUE TITLE
Allow to set service root inside a dispatcher

### ISSUE THREAD

**Issue by dharezlak** [resty-gwt/resty-gwt#201]
For projects which use several different endpoints over CORS the static Defaults.setServiceRoot(String) is not enough. Consider adding a setServiceRoot(String) method to dispatcher's builder parameter for better flexibility.

**Comment by mkadunc** [comment]
I'm experiencing a ClassCastException when specifying the serviceRootKey on the service interface without 'expect' value:
```
@Path("test")
@Produces("application/json")
@Options(serviceRootKey="sandbox")
public interface TestRestService extends DirectRestService {
	@GET @Path("{id}")
	public TestDto getTest(@PathParam("id") String localId);
}
```

```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
    at com.sun.proxy.$Proxy55.expect(Unknown Source)
    at org.fusesource.restygwt.rebind.RestServiceClassCreator.writeMethodImpl(RestServiceClassCreator.java:549)
    at org.fusesource.restygwt.rebind.RestServiceClassCreator.generate(RestServiceClassCreator.java:301)
    at org.fusesource.restygwt.rebind.BaseSourceCreator.create(BaseSourceCreator.java:198)
    at org.fusesource.restygwt.rebind.RestServiceGenerator.generate(RestServiceGenerator.java:39)
    at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
```
It works fine with @Options(expect = {200}, serviceRootKey="sandbox")

**Comment by christianbauer** [comment]
The last problem with the broken @Options parsing I've opened as #244.

I'd also like to set a service root, but dynamically for each service call. The static dispatcher override is not a solution for my case. I'm using the API from a web component, and the user can give me the service base URL she wants to call. Each web component instance can call a different backend.

**Comment by Armageddon-** [comment]
@christianbauer Is there any reason why you don't use [RestServiceProxy#setResource](https://github.com/resty-gwt/resty-gwt/blob/master/restygwt/src/main/java/org/fusesource/restygwt/client/RestServiceProxy.java#L27)?

**Comment by christianbauer** [comment]
Thanks, that helped in my case. I didn't see it in the docs.

**Comment by mkristian** [comment]
guess we can close this
