### ISSUE TITLE
1.4: JsonSubTypes break GWT .cache.html files

### ISSUE THREAD

**Issue by r3use** [resty-gwt/resty-gwt#232]
If you have a service with polymorphic parameters and several defined JsonSubTypes, GWT .cache.html files will change when recompiling the same source.

According to http://www.gwtproject.org/doc/latest/FAQ_DebuggingAndCompiling.html#What it should guaranteed that *"if you recompile your application without changing code, the contents of the output will not change."*

I tracked down the reason to class org.fusesource.restygwt.rebind.JsonEncoderDecoderClassCreator. findJsonSubType stores subtypes in a HashSet which does not guerantee any specific order of its content when iterating over it.

I think this issue is still present in newer versions of resty-gwt.

A possible solution is to sort the List returned by getPossibleTypes in the generate method of JsonEncoderDecoderClassCreator before generating the output.

**Comment by mkristian** [comment]
since you already found a solution - could you just prepare a PR request
for this. not sure how to automatically test this - so it really depends on
manually testing where you are THE person for it ;)

**Comment by r3use** [comment]
Sure.

Do you have any quality/style requirements for PRs?

**Comment by mkristian** [comment]
no - not really. just do not reformat the whole file so the actual diff is
understandable ;)

**Comment by seamusmac** [comment]
@mkristian I guess we can close this too :)
