### ISSUE TITLE
janitorial eclipse warnings: switch on As is missing cases

### ISSUE THREAD

**Issue by vasvir** [resty-gwt/resty-gwt#241]
Hi,
I recently created #240 that fixes obvious eclipse warnings (in my setup).

I haven't included in the above patch a fix that doesn't look obvious enough.

I am referring to JsonEncoderDecoderClassCreator.java around line 226 where there is a **switch** statement  which is missing the two cases below:
* EXISTING_PROPERTY
* EXTERNAL_PROPERTY

I am not familiar with that part of the code and I don't know what's the correct way to handle that.

   Vassilis

**Comment by mkristian** [comment]
warning is better then silently ignoring ;)

thanx
