### ISSUE TITLE
Recursive JsonSubTypes does not detect children/granchildren JsonSubType annotations

### ISSUE THREAD

**Issue by paul-duffy** [resty-gwt/resty-gwt#242]
There already is a unit test that fails in the master branch: org.fusesource.restygwt.client.basic.JsonCreatorWithSubtypesRecursive

**Comment by paul-duffy** [comment]
The issues seems to be caused by [pr:217](https://github.com/resty-gwt/resty-gwt/pull/217). The code that would recursively follow JsonSubTypes was removed. I should have a fix soon.

**Comment by mkristian** [comment]
bit surprised about the failing test but happy to see it fixed :)
