### ISSUE TITLE
Remove hardcoded X-HTTP-Method-Override header

### ISSUE THREAD

**Issue by christianbauer** [resty-gwt/resty-gwt#245]
I'm dealing with a server that is CORS-enabled and doesn't allow X-HTTP-Method-Override. I can't change that and resty-gwt always adds that header. I don't see a way to disable this even with patching the RequestBuilder in a custom @Options dispatcher. The header will not be necessary, it will not be used, it should not be set.

**Comment by sturichardson** [comment]
I too am having this problem and would love a way around it... Is there a work around at least?

**Comment by frami** [comment]
I have the same problem with a jersy backend. A provided a change to turn off this header.
https://github.com/resty-gwt/resty-gwt/pull/263

**Comment by Armageddon-** [comment]
close, because now it is possible with change from frami
