### ISSUE TITLE
Code generation error with a method taking a List as parameter

### ISSUE THREAD

**Issue by ntspkl** [resty-gwt/resty-gwt#247]
I have following client side code:

	@POST
	@Path("/get")
	@Produces(MediaType.APPLICATION_JSON)
	public void get(@FormParam("language") String language,
			@FormParam("keys") List<String> keys,
			MethodCallback<Translation> translations);

Which results in following error at compile time:
               [ERROR] Line 46: expr cannot be resolved to a variable

     @Override
     public java.util.Iterator<String> iterator() {
         final java.util.Iterator<java.lang.String> baseIterator =  final_keys.iterator();
         return new java.util.Iterator<String>() {
             @Override
             public boolean hasNext() {
               return baseIterator.hasNext();
             }
             @Override
             public String next() {
                 return expr;
             }
             @Override
             public void remove() {
                 throw new UnsupportedOperationException();
             }
         };

**Comment by Armageddon-** [comment]
@ntspkl The problem should be solved with #248 and latest release [restygwt-2.0.3.jar](https://repo1.maven.org/maven2/org/fusesource/restygwt/restygwt/2.0.3/restygwt-2.0.3.jar), could you confirm this?

**Comment by Armageddon-** [comment]
No answer for over 3 month, I think we can close.
