### ISSUE TITLE
Incomplete generated xxx_Generated_JsonEncoderDecoder_ class 

### ISSUE THREAD

**Issue by jvence** [resty-gwt/resty-gwt#267]
I've upgraded from resty-gwt from 1.5 to 2.0.3 and started getting compile errors caused by incomplete xxx_Generated_JsonEncoderDecoder_ generated classes. 

Basically the generated class looks like this and is missing setters and return statements:

public class Notes_Generated_JsonEncoderDecoder_ extends org.fusesource.restygwt.client.AbstractJsonEncoderDecoder<com.test.client.Notes> {
  
  public static final Notes_Generated_JsonEncoderDecoder_ INSTANCE = new Notes_Generated_JsonEncoderDecoder_();
  
  public com.google.gwt.json.client.JSONValue encode(com.test.client.Notes value) {
    if( value==null ) {
      return getNullType();
    }
    com.google.gwt.json.client.JSONObject rc = new com.google.gwt.json.client.JSONObject();
  }
  
  public Notes decode(com.google.gwt.json.client.JSONValue value) {
    if( value == null || value.isNull()!=null ) {
      return null;
    }
    com.google.gwt.json.client.JSONObject object = toObject(value);
  }
  
}

It seems that for some reasons the generated JsonEncoderDecoder is failing at some point and creating an invalid class. Reverting to 1.5 shows a complete Generated_JsonEncoderDecoder class.

The Notes class extends an abstract class B and B extends another abstract class A. Class A contains all the necessary JsonSubTypes properties.

Any advice on how to determine what is going wrong?

Thanks

**Comment by mkristian** [comment]
@jvence did find a solution for you problem ? I did not had time to look at your example.
