### ISSUE TITLE
Jackson package inside the resty dependency

### ISSUE THREAD

**Issue by feedm3** [resty-gwt/resty-gwt#269]
Hi guys,
I'm using resty gwt within my project and facing some problems with different versions of jackson. The problem is the jackson dependency inside the resty package (look at the attached image). It's an old version which is not compatible with some other libraries I'm using and I don't know how I can get rid of it. I tried to exclud it with gradle but that doesnt work.
```
providedCompile('org.fusesource.restygwt:restygwt:2.0.3') {
    exclude group: 'com.fasterxml.jackson'
}
```
How can I use restygwt without the "build in" jackson dependency?

![resty-gwt-jackson](https://cloud.githubusercontent.com/assets/7814926/11235185/77b447d4-8dcf-11e5-97db-81cfae1a5919.png)

Thanks in advance and big applaud to that great project :clap:

**Comment by mkristian** [comment]
this jackson classes are packed into the restygwt jar so there is really nothing you can do to exclude this. it is already a proper dependency with https://github.com/resty-gwt/resty-gwt/commit/c648c50e33dab3190df11eca4fcfbd75bda12067. let me find some time and prepare a 2.1.0 release with this fix over the weekend.

**Comment by Armageddon-** [comment]
Release with fix is out.

Also see https://github.com/resty-gwt/resty-gwt/issues/236
