### ISSUE TITLE
@PathParams should always be URL encoded

### ISSUE THREAD

**Issue by falc0r** [resty-gwt/resty-gwt#294]
Full discussion is at https://groups.google.com/forum/#!topic/restygwt/rb09rRqqFLs

I disagree with the "issue" reported in #184 and think that the fix for it, commit 2b07fa9, introduces additional problems.  I propose that the encoding changes in commit 2b07fa9 be reverted.

**Comment by falc0r** [comment]
Created pull request #295

**Comment by mkristian** [comment]
fixde via #295
