### ISSUE TITLE
DirectRestServices don't allow string return values

### ISSUE THREAD

**Issue by falc0r** [resty-gwt/resty-gwt#296]
As it stands now, methods in a DirectRestService can't use "normal" strings as a return value.  The only way this works is if the string returned from the server is valid JSON, but if this is the case then they should probably be using a more well defined complex type anyway.

The cause of this deficiency starts in the DirectRestServiceInterfaceClassCreator, which always uses MethodCallback regardless of the type being returned.  As a result, other classes which inspect the callback type and parse the response text based on it try to convert the text to a JSONValue rather than just passing along the string.  Detecting the return type and requiring a TextCallback if String is found should fix this.

**Comment by mkristian** [comment]
not sure if this is the whole answer. probably needs to look at the Prodcues annotation. the default to text with your PR is probably the right choice.

will keep this one open for now

**Comment by falc0r** [comment]
Are you saying that inspection of the @Produces annotation would dictate which of the MethodCallback interfaces need to be used?  This is something that had I had considered, but I figured that if someone wanted JSON or XML then they should be either using a JsonCallback or XmlCallback to get a JSONValue or Document.  Looking into it a little further, I see now that those types that are client-side only classes.

That being the case, JsonCallback and XmlCallback are out because the server can't return those types.  A plain MethodCallback won't work with a string return value because it will always attempt to convert the string to a JSONValue and then to the type specified as the generic parameter.  OverlayCallback is also out because the type must extend JavaScriptObject.

This means that there is no other option for the callback type except TextCallback, right?  Or do you mean to say that if text/plain is used with a MethodCallback<String> that we should vary the behavior of the parsing?

**Comment by Armageddon-** [comment]
It sounds like the same that https://github.com/resty-gwt/resty-gwt/pull/262 fix.

Try to add this to your module XML:
`<set-property name="restygwt.autodetect.plainText" value="true" />`

**Comment by Armageddon-** [comment]
I had some time to check the changes. The result is, it breaks #262.

With #314 i added tests for DirectRestService and revert the changes from #297.

**Comment by mkristian** [comment]
in order to use auto-detection on strings you need to set in your XZY-gwt.xml
```xml
<set-property name="restygwt.autodetect.plainText" value="true" />
```

I guess we can close this issue now.
