### ISSUE TITLE
Can't modify HTTP request body

### ISSUE THREAD

**Issue by JeromeDesseaux** [resty-gwt/resty-gwt#299]
Hi everyone, 

I'm trying to make GWT communicate with a C# REST API. This API is waiting (on POST request) a '=' character before the JSON serialized object within the HTTP Body. 

`={"attribute":"value", "otherOne":"otherValue"}`

But RestyGWT is sending pure JSON. Is this a bug or there is a way I didn't check? 

Thanks

**Comment by mkristian** [comment]
that is the first time (which does not mean much) I see this ```=```. restygwt can not prepend any data in the message body. feel free to dig into the code - maybe it is easy to implement, not sure.

any idea why this C# REST API is expecting this ?

**Comment by JeromeDesseaux** [comment]
I have no idea at all! I've been surprised to! It seems this is something due to the [FromBody] annotation which is parsing the HTTP body into a C# object. I'm new to both C# and GWT. But I'll try to find a way to mark it work. Modifying my C# services or making a PR of that projet. 

Anyway, thanks for your help :)

**Comment by mkristian** [comment]
@JeromeDesseaux closing thins as it seems to be some "edge case". please feel free to reopen if it is still an issue for you.
