### ISSUE TITLE
Invalid decoder generated for fields with java.* type from GWT super-source path

### ISSUE THREAD

**Issue by glucas** [resty-gwt/resty-gwt#305]
An invalid EncoderDecoder class is generated in the following case:
- Response bean has a field of a type java.net.URI
- The source for java.net.URI is added to via a GWT super-source module entry. 

GWT compile fails. Looking at the generated URI_Generated_JsonEncoderDecoder_ file, the decode() method is returning the non-qualified type 'URI', which is not found because the encoder itself is put in the package "open.java.net".

I presume this same issue would apply to any java.* fields that are added via super-source.

**Comment by mkristian** [comment]
fixed via #306
