### ISSUE TITLE
Generated classes has very long names resulting compilation problems

### ISSUE THREAD

**Issue by lucasam** [resty-gwt/resty-gwt#316]
The Encoders and Decoders generated by resty has a standard name derived from the basic type.
When generics are used the generic class names are incorporated to class names, and eventually the final class name is larger than 256 characters resulting in filesystem/compilation errors.

Example: 
On service method

@Path("sericeName")
public List<ClassName> getOperacoes(Tuple6<A, B,C,D, E,F> args)  {

Generates a decoder called
Tuple6__full_package_class_A_full_package_class_B_full_package_class_C_full_package_class_D_full_package_class_E_full_package_class_F_Generated_JsonEncoderDecoder_

This if this class is bigger than 256 characters a compilation problem occurs

**Comment by lucasam** [comment]
I already fixed this issue. Will submit a pull request today

**Comment by mkristian** [comment]
fixed via #317
