### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by 200Puls** [resty-gwt/resty-gwt#321]
It has been more than 6 month since the last official relase of maven artifacts and a lot of fixes and improvements have been done since. How about a new release?

**Comment by mkristian** [comment]
I have restricted internet this and no internet next week. so expect the
next release in beginning of july !

**Comment by mkristian** [comment]
worked on the release last weekend and ran into some merge issues with the gwtjackson patch. not sure if it just the merge or something deeper. since I do not have much time during the week . . . next weekend.

**Comment by mkristian** [comment]
released for some time now. did not send announcement to list but I can close this now.
