### ISSUE TITLE
improve callback interface for lambda?

### ISSUE THREAD

**Issue by nile** [resty-gwt/resty-gwt#366]
Thank for your great work, at first!
But ...
when i use the callback, i can use java 8 lambda expressions.
can you seperate the `MethodCallback` into `FailureCallback `and `SuccessCallback`
Then ,the code should more simple.

```
service.list("some", (m,t)->{},(m,list)->{});
```

Thanks very much!

**Comment by jerith666** [comment]
You can make a builder that'll let you do something like this:

```
service.list("some",
             MethodCallback.withSuccess((m,list)->{})
                           .withFailure((m,t)->{}));
```

I just pushed a quick commit that adds this right into `MethodCallback` ... but I had to move RestyGwt from `-source 1.6` to `-source 1.8` to make it compile.

**Comment by nile** [comment]
great job!

**Comment by mkristian** [comment]
@nile @jerith666 I am happy to merge all your changes to resty-gwt if you submit the PR against resty-gwt/resty-gwt !

github closes an issues if it was referenced by a PR and this PR get merged. so I am not sure if closing this issue was intentionally.

**Comment by jerith666** [comment]
Oh, I assumed moving to `-source 1.8` was a bridge too far for a small convenience feature like this.  Will open a PR!  :)
