### ISSUE TITLE
Feature Request: add automatic generation of sub-resource locator methods

### ISSUE THREAD

**Issue by yarrumretep** [resty-gwt/resty-gwt#56]
Ideally, RestyGWT would be able to generate proxy methods that would emulate synchronous clients' JAX-RS sub-resource locator methods.  These methods might look something like this in Resty async version:

``` java
public interface Book
{
   @GET
   @Path("/title")
   void getTitle(MethodCallback<String> cb);

   @Path("{number}")
   Chapter getChapter(@PathParam("number") int number);
}

public interface Chapter
{
   @GET
   @Path("title")
  void getTitle(MethodCallback<String> cb);

   @GET
   @Path("body")
   void getBody(MethodCallback<String> cb);
}

```

As you can see, the Book.getChapter(int) method is not asynchronous and does not have an HTTP method annotation (@GET, @POST, etc).  The code generator could generate code that would create the appropriate sub-resource URL for this and return a new proxy for the subresource.

I'd be happy to implement this if you give me the thumbs up that you think its a decent idea.

Many of the JAX-RS proxy generation clients do the analogous operation against JAX-RS annotated shared interfaces.

Thanks for Resty!  It ROCKS!

**Comment by glucas** [comment]
Would it be possible to extend this to work for DirectRestService interfaces as well? Currently sub-resource locators only seem to work for the RestService interface.
