### ISSUE TITLE
Adding a new XHR2 RequestDispatcher

### ISSUE THREAD

**Issue by imrabti** [resty-gwt/resty-gwt#94]
The XHR2 / Cors is avaible on most Browser today, with this we can to cross site requests to other servers the calls aren't limited to 'GET' methods only (like JSONP).

I would really a new custom RequestDispather for RestGwt implementing calls over the XHR2.

Ref for the XHR2 for GWT : http://code.google.com/p/chrome-rest-client/
Browser support status : http://caniuse.com/#feat=xhr2

**Comment by Armageddon-** [comment]
No update for over 3 years. Like described in #177 CORS branch will be delete sooner or later.
